#!/usr/bin/env bash
# Displays the content of the current directory in list format.
# Only displays the part of the name after the first dash

command=$(ls)
for i in $command
do
    echo "$i" | cut -d '-' -f2
done
