#!/usr/bin/env bash
# Display numbers from 1 to 100 in list format.
#  Displays "FizzBuzz" when the number is a multiple of 3 and 5
# Display "Fizz" when the number is a multiple of 3.
# Display "Buzz" when the number is a multiple of 5
# other, display the number.

i=1
while [ $i -le 100 ]
do
    if [ $((i % 3)) -eq 0 ] && [ $((i % 5)) -eq 0 ]
    then
        echo "FizzBuzz"
    elif [ $((i % 3)) -eq 0 ]
    then
        echo "Fizz"
    elif [ $((i % 5)) -eq 0 ]
    then
        echo "Buzz"
    else
        echo "$i"
    fi
    i=$((i+=1))
done
